// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RL.Data;

#nullable disable

namespace RL.Data.Migrations
{
    [DbContext(typeof(RLContext))]
    [Migration("20260407093249_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("RL.Data.DataModels.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("RL.Data.DataModels.PlanProcedure", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId", "ProcedureId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("PlanProcedures");
                });

            modelBuilder.Entity("RL.Data.DataModels.PlanProcedureUser", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId", "ProcedureId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PlanProcedureUsers");
                });

            modelBuilder.Entity("RL.Data.DataModels.Procedure", b =>
                {
                    b.Property<int>("ProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcedureTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ProcedureId");

                    b.ToTable("Procedures");

                    b.HasData(
                        new
                        {
                            ProcedureId = 1,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Procedure 1",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 2,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Procedure 2",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProcedureId = 3,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcedureTitle = "Procedure 3",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RL.Data.DataModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreateDate = new DateTime(2026, 4, 7, 9, 32, 49, 722, DateTimeKind.Utc).AddTicks(7805),
                            Name = "Nick Morrison",
                            UpdateDate = new DateTime(2026, 4, 7, 9, 32, 49, 722, DateTimeKind.Utc).AddTicks(7807)
                        },
                        new
                        {
                            UserId = 2,
                            CreateDate = new DateTime(2026, 4, 7, 9, 32, 49, 722, DateTimeKind.Utc).AddTicks(7810),
                            Name = "Scott Cassidy",
                            UpdateDate = new DateTime(2026, 4, 7, 9, 32, 49, 722, DateTimeKind.Utc).AddTicks(7811)
                        },
                        new
                        {
                            UserId = 3,
                            CreateDate = new DateTime(2026, 4, 7, 9, 32, 49, 722, DateTimeKind.Utc).AddTicks(7812),
                            Name = "Tony Bidner",
                            UpdateDate = new DateTime(2026, 4, 7, 9, 32, 49, 722, DateTimeKind.Utc).AddTicks(7813)
                        },
                        new
                        {
                            UserId = 4,
                            CreateDate = new DateTime(2026, 4, 7, 9, 32, 49, 722, DateTimeKind.Utc).AddTicks(7814),
                            Name = "Patryk Skwarko",
                            UpdateDate = new DateTime(2026, 4, 7, 9, 32, 49, 722, DateTimeKind.Utc).AddTicks(7815)
                        });
                });

            modelBuilder.Entity("RL.Data.DataModels.PlanProcedure", b =>
                {
                    b.HasOne("RL.Data.DataModels.Plan", "Plan")
                        .WithMany("PlanProcedures")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RL.Data.DataModels.Procedure", "Procedure")
                        .WithMany()
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("RL.Data.DataModels.PlanProcedureUser", b =>
                {
                    b.HasOne("RL.Data.DataModels.User", "User")
                        .WithMany("AssignedPlanProcedures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RL.Data.DataModels.PlanProcedure", "PlanProcedure")
                        .WithMany("AssignedUsers")
                        .HasForeignKey("PlanId", "ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanProcedure");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RL.Data.DataModels.Plan", b =>
                {
                    b.Navigation("PlanProcedures");
                });

            modelBuilder.Entity("RL.Data.DataModels.PlanProcedure", b =>
                {
                    b.Navigation("AssignedUsers");
                });

            modelBuilder.Entity("RL.Data.DataModels.User", b =>
                {
                    b.Navigation("AssignedPlanProcedures");
                });
#pragma warning restore 612, 618
        }
    }
}
